maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 100)
while (true) {
    if (maqueen.Ultrasonic(PingUnit.Centimeters) < 10) {
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 120)
        maqueen.motorStop(maqueen.Motors.M2)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 107)
        basic.pause(2500)
        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 120)
        maqueen.motorStop(maqueen.Motors.M1)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 101)
        basic.pause(2500)
        maqueen.motorStop(maqueen.Motors.M1)
        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 120)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 109)
        basic.pause(2500)
        maqueen.motorStop(maqueen.Motors.M2)
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 117)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 101)
        basic.pause(2500)
        maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 117)
        maqueen.motorStop(maqueen.Motors.M2)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 109)
        basic.pause(2500)
        maqueen.motorStop(maqueen.Motors.M1)
        maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 120)
        basic.pause(800)
        maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 109)
        basic.pause(2500)
        maqueen.motorStop(maqueen.Motors.All)
    }
}
